### ISSUE TITLE
questions about equation 4 and warping

### ISSUE THREAD

**Issue by HaoDot** [shangwei5/D2Net#4]
Hi @shangwei5 , nice work for image deblurring. It is a clever idea to utilize existing adjacent sharp frame near to the blurry image.

However, there are a few questions confusing me a lot. I hope that you can provide me some advice thx.

- a mismatch between equation 4 and your warping code

According to the equation 4 in your paper, by using forward optical flow ![](https://latex.codecogs.com/svg.image?\\:u_{\rightarrow&space;i}), which means the displacement from NSF ![](http://latex.codecogs.com/gif.latex?\\:G_{i}^{-}) to  blurry img ![](http://latex.codecogs.com/gif.latex?\\:B_{i}), you align ![](http://latex.codecogs.com/gif.latex?\\:G_{i}^{-}) with ![](http://latex.codecogs.com/gif.latex?\\:B_{i}). It did make sense. However, as far as I know, most warping functions use backward warping, which means using the optical flow from ![](http://latex.codecogs.com/gif.latex?\\:B_{i}) to ![](http://latex.codecogs.com/gif.latex?\\:G_{i}^{-}) and warp  ![](http://latex.codecogs.com/gif.latex?\\:G_{i}^{-}) to the coordinate of target frame ![](http://latex.codecogs.com/gif.latex?\\:B_{i}). 

From my perspective, the warping function in your code is backward warping, [https://github.com/shangwei5/D2Net/blob/76a44beab13c2b8e0d31aef89b3a3a60e691f84f/code/model/flow_pwc.py#L56](url)  however, the optical flows are not the corresponding ones. So is equation 4 in your paper. Chances are that I have got it wrong. Please help me to understand it better, THX!

- a question of ![](http://latex.codecogs.com/gif.latex?\\:G_{i}^{+}) in equation 4

It seems that it should be ![](http://latex.codecogs.com/gif.latex?\\:G_{i}^{+}) in the second row of equation 4. I don't know if there is something wrong with my pdf reader.

- a question about synthesizing blur

In your setting of deblurring, the number of sharp images to average varies from 1 to 15 in GoPro. the generated frame is still sharp despite the number of averaging frames being 5. However, it seems that you didn't interpolate imgs between current sharp frames. I don't know if the generated frame keeps sharp after averaging the 5 original sharp frames and the interpolated imgs between them. If following this setting, I wonder if D2net can still alleviate the neighboring sharp frame.

**Comment by shangwei5** [comment]
Thank you for your attention to our work！
1）We warp G+ to Bi, and G- to Bi with backward warping. And I check the paper ...the arrow is indeed reversed in paper, your understanding is right. I'm sorry about that.

2)We didn't interpolate frames, because the GOPRO blur data provided by official is the same. We just follow them, and original GOPRO video is 240FPS.  
Our definition of sharp frame: considering the real situation, it is not required to be completely sharp, but the blur degree is not heavy, and it is enough to guide the heavy blurry frames restoration.
"I don't know if the generated frame keeps sharp after averaging the 5 original sharp frames and the interpolated imgs between them. "  that means you want to average <5*N(N is your interpolation times) frames as sharper frame? Although I didn't try it, it may increase blur degree and may not be used to guide the restoration of the current frame.

**Comment by HaoDot** [comment]
Got it! THX for replying immediately!
